hw.i915kms.enable_hangcheck=1
hw.i915kms.reset=3
hw.i915kms.fastboot=1
hw.acpi.cpu.cx_lowest="C1"
hw.acpi.acline=1
ipv6_activate_all_interfaces="NO"
autoboot_delay="1"
verbose_loading="NO"
hint.acpi_throttle.0.disabled="1"
hint.p4tcc.0.disabled="1"
