dev.cpu.0.freq=1500
dev.cpu.1.freq=1500
vm.swap_idle_threshold1=2
vm.swap_idle_threshold2=10
vm.pageout_stats_enable=1
vm.overcommit=0
vm.pmap_pti=0
vfs.read_max=16
vfs.atime=0
vfs.vmiodirenable=1
vfs.dirhash_maxmem=2097152
vfs.ufs.dirhash_maxmem=2097152
kern.ipc.somaxconn=1024
net.inet.tcp.delayed_ack=0
net.inet.tcp.sendspace=65536
net.inet.tcp.recvspace=65536
net.inet.tcp.sendbuf_max=8388608
net.inet.tcp.recvbuf_max=8388608
net.inet.tcp.mssdflt=1460
net.inet.tcp.tso=1
net.inet.tcp.lro.enable=1
net.link.ether.inet.max_age=600
net.inet.ip.forwarding=0
net.inet.ip.redirect=0
net.inet6.ip6.forwarding=0
net.inet6.ip6.accept_rtadv=0
net.inet6.ip6.auto_linklocal=0
kern.sched.preempt_thresh=224
kern.sched.slice=1
machdep.mitigations.ibrs.disable=1
machdep.mitigations.ssb.disable=1
machdep.mitigations.mds.disable=1
hw.ibrs_disable=1
machdep.mitigations.taa.enable=0
hw.i915kms.enable_hangcheck=1
hw.i915kms.reset=3
hw.i915kms.fastboot=1
hw.snd.latency=2
hw.snd.vpc_reset=0
kern.ipc.shm_use_phys=1
kern.random.fortuna.min_entropy=0
