net.inet.tcp.delayed_ack=0
net.inet.tcp.sendspace=65536
net.inet.tcp.recvspace=65536
net.inet.tcp.sendbuf_max=8388608
net.inet.tcp.recvbuf_max=8388608
net.inet.tcp.mssdflt=1460
net.inet.tcp.tso=1
net.link.ether.inet.max_age=600
net.inet.ip.forwarding=0
net.inet.ip.redirect=0
machdep.mitigations.ibrs.disable=1
machdep.mitigations.ssb.disable=1
machdep.mitigations.mds.disable=1
hw.ibrs_disable=1
machdep.mitigations.taa.enable=0
hw.snd.latency=2
hw.snd.vpc_reset=0
kern.ipc.shm_use_phys=1
